### ISSUE TITLE
openEO: API, clients, hub

### ISSUE THREAD

**Issue by nuest** [Geosoft2/geosoft2-2020#7]

**Comment by FelixGI1516** [comment]
Das würde ich dann behandeln

**Comment by nuest** [comment]
Prima! Bitte zeitnah anschauen und mit @jana2308walter absprechen, dass ihr wenig Überschneidungen habt. Ich würde Vorschlagen, dein Thema kommt zuerst, aber da könnt ihr auch gerne mitentscheiden.

**Comment by nuest** [comment]
Vielleicht hilfreich bei der Vorbereitung (ich gehe davon aus, dass die Videos nachträglich noch veröffentlicht werden): https://openeo.org/news/2020-09-02-openeo-user-workshop.html

**Comment by nuest** [comment]
https://twitter.com/matthmohr/status/1223965293954945025?s=09)

**Comment by m-mohr** [comment]
> Vielleicht hilfreich bei der Vorbereitung (ich gehe davon aus, dass die Videos nachträglich noch veröffentlicht werden): https://openeo.org/news/2020-09-02-openeo-user-workshop.html

Leider aus datenschutzrechtlichen Gründen nicht möglich...
